site:
  title: Accor DocOps
  url: http://localhost:8080
content:
  sources:
    - url: ./
      start_path: content
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public

