site_name: Accor DocOps
site_description: ITIL-aligned documentation hub
site_url: https://example.github.io/accor-docops
theme:
  name: material
  logo: media/itil-catalog.png
  favicon: media/itil-catalog.png
  features:
    - navigation.sections
    - navigation.path
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: amber
plugins:
  - search
  - glightbox
  - section-index
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: de
          name: Deutsch
          build: false
        - locale: es
          name: Español
          build: false
        - locale: ru
          name: Русский
          build: false
      docs_structure: folder
  - tags
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
nav:
  - EN:
      - Home: en/index.md
      - Tags: en/tags.md
      - Browse by Audience: en/by-audience/index.md
      - Browse by Type: en/by-type/index.md
      - Browse by Owner: en/by-owner/index.md
      - ITIL:
          - Incident Management: en/itil/incident/index.md
          - Problem Management: en/itil/problem/index.md
          - Change Enablement: en/itil/change/index.md
          - Configuration Management (CMDB): en/itil/cmdb/index.md
          - Service Catalog Management: en/itil/service-catalog/index.md
      - Knowledge Base (KB): en/kb/index.md
      - Ops (Runbooks): en/ops/index.md
      - DevOps: en/devops/index.md
      - Governance:
          - Overview: en/governance/index.md
          - Taxonomy: en/governance/taxonomy.md
          - Architecture: en/governance/architecture/README.md
      - Onboarding: en/onboarding/index.md
extra:
  social:
    - icon: material/book-open-page-variant
      link: https://example.github.io/accor-docops
  consent:
    title: Cookies
    description: Internal demo site.
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr
    - name: Deutsch
      link: /de/
      lang: de
    - name: Español
      link: /es/
      lang: es
    - name: Русский
      link: /ru/
      lang: ru
docs_dir: docs
